### ISSUE TITLE
Java 8 like Functional methods in Optional

### ISSUE THREAD

**Issue by NikoYuwono** [android10/arrow#9]
Fernando, I'm planning to use arrow in my porject but then I realize there are no Functional methods in Optional like Java 8's Optional (map, flatmap, etc). Is there any plan to add that feature? Or do you think adding that features don't match with the purpose of this library?

Thanks!

**Comment by android10** [comment]
@NikoYuwono unfortunately there are no plans. Most of the classes have been grabbed from Guava and the purpose of the library is to keep it lightweight. 

That does not mean new functionalities can be added if they make sense and are useful.

**Comment by NikoYuwono** [comment]
I see, then it'll be different from the purpose of this library. Thanks for the answer!
